language: node_js
node_js:
- '6'
services: mongodb
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: mrls@live.cn
  password:
    secure: Ef7n7wPGdDcGFFerB310YWjCzU8LmBXW0OSoLpMMzoCRgflgXN39JtMWwPYKxDEl3pUZCpqAxPNH3gCuPfbmKOt38TBtfMqEj33znePybl2pTAnwdS8yTbLIv/3o19SLOLaFba+fqtuFP6xwCoyVtzNGsaHsh688n5239gRdx6reRjWGA1W/kip3Bma1Xlh4Gw/u1uYJOEI+kbjobco/ZavW6EPRxlEIzw5rOdypht8Otnt6PX5n3MLCCmAOOhssSx0awAdK1YBu6+OC+TeFccrpeRVbHbozzKro3Z8q8WkN0jNQ3VKWhgUwnuVstpbGYkbqJxUDQbnGhlGYKFHmG8EwBlnt1Q6+jWsKjLBRPZXWHwURjy5YZySSodTL+0uL4QCln6ad3FnaJTu4DxuzyefluGZ7XHxxkFmeFtCsI7jQ6iHVXcRatziTfAlBfZ2u5yMpEfrrcAHs/TYDHpVwEwU4R+wfHDe4GqvheXZ3TFVN7878TiNj4Ef/eVEwttJNquhnHYDiYaDHE21HSHcVDFkighRpoWoOfMqzGMI3p8+EnhacZnnSjtzZP3B/q7FvdoCQXwVWogvm/VF5GSH1h98Gk2pB1HsSZrrjCbEiQpGm4OAsSirWWv9IIYGMnCFiYGGI+3CiyaGqkZp+LpvoBSpPZtVmpRr4StDAd1vZqBY=
  organization: mrls-org
  space: development
  on:
    repo: Soontao/discoverer
env:
  global:
    secure: Ri/XKJxJHVoLlF/u+mjV3NNI3HO1VcEVImoeFPr8L3vbE00AU4tI3sNyn0wgST4Rjm1CKUuBHUBcS2XC+xrl9Nl68+wCenBKh1SH02PwNNEcgek2IjLuycOBmDN3hI9rwy5E4aCNF+YsFPX5GJrOARyK8x68Dr/bOSWGNjLNGQtyBaKiiXx6FDcfCok4i9ACTThttv9eivv3CE5o4uYjR1wtP2XHj8jw2Prh09zvj9HPeKHPYYrPR+Q8mnRhH05CQ708LtSVmUllQn+/QaTbKxEaYh5+8Juo9+HQU1hZIO0HFdhE+KVRaL1CpBbTzC+ZL2kokAOAmuPPReZPjev/5Unw8WiIkvtc2AjDucae1xnGRWy8NUso8VHlEagg6yCW58mfAaBIRSyauG5G/E9FqlHHYf5TeP4F8bk6i5XkW50uDufDg4JrEbuIWsjkEYXnUXBEZBxe+k1zC/Y9R0kWrAklrASaPFN6jEvNkKMRTSv4y2+fRhEj4jGevbD5n0QQy0skS/ORuGlqe5rBu8vjRiDui62c8d++0Iyhw64R+l8hY5uLkRQmV4dlACtam7Nn0mKWUPEHVVruDjsaEe+GsdrT2QsdzdTtEKMg18XZjw6ipusUtiEyI5XDZnwsX6YzpwiuyEjz763+1eZcPd10FsNyQYR0pTjslq/VuXlvNGY=
